config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  devise_for :users, controllers: {registrations: :registrations}

  get "profile/",    to: "users#my_profile", as: :my_profile_user
  get "settings/",   to: "users#setting",    as: :settings_user
  get "users/:id",   to: "users#show",       as: :profile_user

  get  "match/", to: "matches#index", as: :matches
  post "match/", to: "matches#create"

  get  "chat/",         to: "chat#inbox",        as: :inbox_chat
  get  "chat/:id",      to: "chat#room",         as: :room_chat
  post "chat/:id/send", to: "chat#send_message", as: :send_message_chat
  get  "chat/:id/other_messages", to: "chat#other_messages"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/chat_controller.rb
# frozen_string_literal: true

class ChatController < ApplicationController
  def inbox
    @chat_rooms = current_user.chat_rooms
  end

  def room
    @chat_room = ChatRoom.find(params[:id])

    # Handle unauthorized user
    render nothing: true, status: :unauthorized unless @chat_room.users.exists?(current_user.id)

    @other_user = @chat_room.users.where.not(id: current_user.id).first
    @other_user_last_message_datetime = DateTime.now
    @message = ChatRoomMessage.new
  end

  def send_message
    @chat_room = ChatRoom.find(params[:id])

    @message = ChatRoomMessage.new(message_params)
    @message.chat_room = @chat_room
    @message.user = current_user

    @message.save!
  end

  def other_messages
    chat_room = ChatRoom.find(params[:id])

    # Handle unauthorized user
    render nothing: true, status: :unauthorized unless chat_room.users.exists?(current_user.id)

    last_message_datetime = DateTime.iso8601(params[:last_message_datetime])

    new_messages = chat_room
      .new_messages(last_message_datetime)
      .where.not(user_id: current_user.id)

    new_last_message_datetime = new_messages.last ? new_messages.last.created_at.iso8601(10) : last_message_datetime.iso8601(10)

    render json: {
      new_messages: new_messages,
      last_message_datetime: new_last_message_datetime,
    }
  end

  private

    def message_params
      params.require(:chat_room_message).permit(:message)
    end
end

app/views/chat/inbox.html.erb
<%= render "shared/navbars/chat_inbox" %>

<div class="chat-inbox">
  <% @chat_rooms.each do |chat_room| %>
    <% other_user = chat_room.users.where.not(id: current_user.id).first %>
    <% last_message = chat_room.messages.last %>

    <%= link_to room_chat_path(chat_room) do %>
      <div class="chat-inbox__card">
        <picture class="chat-inbox__avatar">
          <%= cl_image_tag other_user.profile_picture %>
        </picture>
        <div class="chat-inbox__details">
          <div class="chat-inbox__details-top">
            <div class="chat-inbox__user-name"><%= other_user.name %></div>
            <div class="chat-inbox__message-datetime">
              <% if last_message %>
                <%= last_message.created_at.strftime("%I:%M %p") %>
              <% end %>
            </div>
          </div>
          <div class="chat-inbox__message">
            <% if last_message %>
              <%= last_message.message[0..40] %>
              <!-- figure out the way to limit the characters of the message  -->
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chat/room.html.erb
<%= render "shared/navbars/chat" %>

<div class="chat-room">

  <%= content_tag :div, class: "chat-room__data hide", data: { otheruserlastmessagedatetime: @other_user_last_message_datetime.iso8601(10) } do %>
  <% end %>

  <div class="chat-room__box">
    <% @chat_room.messages.each do |message| %>
      <% user_is_me = message.user == current_user %>
      <div class="chat-room__message-box <%= user_is_me ? "chat-room__message-box--me" : "chat-room__message-box--not-me" %>">
        <span class="chat-room__message <%= user_is_me ? "chat-room__message--me" : "chat-room__message--not-me" %>">
          <%= message.message %>
        </span>
      </div>
    <% end %>
  </div>

  <%= simple_form_for @message, url: send_message_chat_path(@chat_room, format: :json), remote: true, html: { class: "chat-room__form" } do |f| %>
    <%= f.input :message, input_html: { class: "chat-room__message-input" }, label: false %>
    <%= image_submit_tag "icon-send-turqoise.png", class: "chat-room__message-send" %></p>
  <% end %>

</div>