config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  devise_for :users, controllers: {registrations: :registrations}

  get "profile/",    to: "users#my_profile", as: :my_profile_user
  get "settings/",   to: "users#setting",    as: :settings_user
  get "users/:id",   to: "users#show",       as: :profile_user

  get  "match/", to: "matches#index", as: :matches
  post "match/", to: "matches#create"

  get  "chat/",         to: "chat#inbox",        as: :inbox_chat
  get  "chat/:id",      to: "chat#room",         as: :room_chat
  post "chat/:id/send", to: "chat#send_message", as: :send_message_chat
  get  "chat/:id/other_messages", to: "chat#other_messages"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/navbars/_chat.html.erb
<div class="navbar-dev-buddy">
  <%= link_to inbox_chat_path, class: "navbar-dev-buddy__link navbar-dev-buddy__link--center" do %>
    <%= image_tag "icon_back.png" %>
  <% end %>
  <div class="chat-room__other_user_name">
    <%= other_user = @chat_room.users.find { |u| u != current_user }.name %>
  </div>
  <div></div>
</div>

<div class="navbar-dev-buddy__spacer"></div>

app/views/shared/navbars/_chat_inbox.html.erb
<div class="navbar-dev-buddy">

  <%= link_to my_profile_user_path, class: "navbar-dev-buddy__link navbar-dev-buddy__link--center" do %>
    <%= image_tag "icon_profile.png" %>
  <% end %>


  <%= link_to "Chats", inbox_chat_path, class: "navbar-dev-buddy__link" %>

  <div></div>
</div>

<div class="navbar-dev-buddy__spacer"></div>

app/views/shared/navbars/_main.html.erb
<div class="navbar-dev-buddy">

  <%= link_to my_profile_user_path, class: "navbar-dev-buddy__link navbar-dev-buddy__link--center" do %>
    <%= image_tag "icon_profile.png" %>
  <% end %>

  <%= link_to "Matches", matches_path, class: "navbar-dev-buddy__link" %>

  <%= link_to inbox_chat_path, class: "navbar-dev-buddy__link navbar-dev-buddy__link--center" do %>
    <%= image_tag "icon_message.png" %>
  <% end %>

</div>

<div class="navbar-dev-buddy__spacer"></div>

app/views/shared/navbars/_profile.html.erb
<div class="navbar-dev-buddy">

  <%= link_to matches_path, class: "navbar-dev-buddy__link" do %>
   <%= image_tag "icon_back.png" %>
  <% end %>


  <%= link_to settings_user_path, class: "navbar-dev-buddy__link" do %>
    <%= image_tag "icon_settings.png"  %>
  <% end %>

</div>

<div class="navbar-dev-buddy__spacer"></div>

app/views/shared/navbars/_settings.html.erb
<div class="navbar-dev-buddy">

  <%= link_to root_path, class: "navbar-dev-buddy__link" do %>
   <%= image_tag "icon_back.png" %>
  <% end %>

  <%= link_to "Settings", settings_user_path, class: "navbar-dev-buddy__link" %>

  <div></div>

</div>

<div class="navbar-dev-buddy__spacer"></div>

app/views/shared/navbars/_signin-login.html.erb
<div class="navbar-dev-buddy">

  <%= link_to root_path, class: "navbar-dev-buddy__link" do %>
   <%= image_tag "icon_back.png" %>
  <% end %>

</div>

<div class="navbar-dev-buddy__spacer"></div>